kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-pvc
  namespace: monitoring
  annotations:
    volume.beta.kubertenes.io/storage-class: vsphere-slow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: vsphere-slow
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: alertmanager-pvc
  namespace: monitoring
  annotations:
    volume.beta.kubertenes.io/storage-class: vsphere-slow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: vsphere-slow
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-pvc
  namespace: monitoring
  annotations:
    volume.beta.kubertenes.io/storage-class: vsphere-fast
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: vsphere-fast


